# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4423e26d5db9d067a8f978706ed922a5edef15227f6bfc67dc728352a7b50780d8e946709425f4c086a04f5b10ab34709c7e50badbad35e05c35ce067dec96a4

test:
  secret_key_base: 2dd11cb855100b0455c38dcee7b1533e53f8d9cdb6ff6b3cc3e4c7b1cbd5b967794e4a99cb753203919973dd7b7099c05bd8fc07757405eb0ac16bc4a7747460

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
